function Coeff = Tire_Coefficients(mfparams, type)
%#codegen
% Returns a vector of Magic Formula coefficients for the requested type.
% Compatible with Simulink code generation (no dynamic field access).

switch lower(type)
    case 'c_long'
        Coeff = [
            mfparams.PCX1(1), ...
            mfparams.PDX1(1), mfparams.PDX2(1), mfparams.PDX3(1), ...
            mfparams.PEX1(1), mfparams.PEX2(1), mfparams.PEX3(1), mfparams.PEX4(1), ...
            mfparams.PKX1(1), mfparams.PKX2(1), mfparams.PKX3(1), ...
            mfparams.PHX1(1), mfparams.PHX2(1), ...
            mfparams.PVX1(1), mfparams.PVX2(1), ...
            mfparams.PPX1(1), mfparams.PPX2(1), mfparams.PPX3(1), mfparams.PPX4(1), ...
            mfparams.RBX1(1), mfparams.RBX2(1), mfparams.RBX3(1), ...
            mfparams.RCX1(1), ...
            mfparams.REX1(1), mfparams.REX2(1), mfparams.RHX1(1) ...
        ];

    case 'c_lat'
        Coeff = [
            mfparams.PCY1(1), ...
            mfparams.PDY1(1), mfparams.PDY2(1), mfparams.PDY3(1), ...
            mfparams.PEY1(1), mfparams.PEY2(1), mfparams.PEY3(1), mfparams.PEY4(1), mfparams.PEY5(1), ...
            mfparams.PKY1(1), mfparams.PKY2(1), mfparams.PKY3(1), mfparams.PKY4(1), mfparams.PKY5(1), mfparams.PKY6(1), mfparams.PKY7(1), ...
            mfparams.PHY1(1), mfparams.PHY2(1), ...
            mfparams.PVY1(1), mfparams.PVY2(1), mfparams.PVY3(1), mfparams.PVY4(1), ...
            mfparams.RBY1(1), mfparams.RBY2(1), mfparams.RBY3(1), mfparams.RBY4(1), ...
            mfparams.RCY1(1), ...
            mfparams.REY1(1), mfparams.REY2(1), ...
            mfparams.RHY1(1), mfparams.RHY2(1), ...
            mfparams.RVY1(1), mfparams.RVY2(1), mfparams.RVY3(1), mfparams.RVY4(1), mfparams.RVY5(1), mfparams.RVY6(1), ...
            mfparams.PPY1(1), mfparams.PPY2(1), mfparams.PPY3(1), mfparams.PPY4(1), mfparams.PPY5(1) ...
        ];

    case 'c_align'
        Coeff = [
            mfparams.QBZ1(1), mfparams.QBZ2(1), mfparams.QBZ3(1), mfparams.QBZ4(1), mfparams.QBZ5(1), mfparams.QBZ9(1), mfparams.QBZ10(1), ...
            mfparams.QCZ1(1), ...
            mfparams.QDZ1(1), mfparams.QDZ2(1), mfparams.QDZ3(1), mfparams.QDZ4(1), mfparams.QDZ6(1), mfparams.QDZ7(1), mfparams.QDZ8(1), mfparams.QDZ9(1), mfparams.QDZ10(1), mfparams.QDZ11(1), ...
            mfparams.QEZ1(1), mfparams.QEZ2(1), mfparams.QEZ3(1), mfparams.QEZ4(1), mfparams.QEZ5(1), ...
            mfparams.QHZ1(1), mfparams.QHZ2(1), mfparams.QHZ3(1), mfparams.QHZ4(1), ...
            mfparams.SSZ1(1), mfparams.SSZ2(1), mfparams.SSZ3(1), mfparams.SSZ4(1), ...
            mfparams.PPZ1(1), mfparams.PPZ2(1) ...
        ];

    case 'c_overt'
        Coeff = [
            mfparams.QSX1(1), mfparams.QSX2(1), mfparams.QSX3(1), mfparams.QSX4(1), ...
            mfparams.QSX5(1), mfparams.QSX6(1), mfparams.QSX7(1), mfparams.QSX8(1), ...
            mfparams.QSX9(1), mfparams.QSX10(1), mfparams.QSX11(1), mfparams.QSX12(1), ...
            mfparams.QSX13(1), mfparams.QSX14(1) ...
        ];

    otherwise
        error('Unknown coefficient type: %s', type);
end

end
