function Coeff = Tire_Scaling_Factors(mfparams, type)
%#codegen
% Returns Magic Formula scaling factors for the requested type.
% Compatible with Simulink code generation (no dynamic field access).

switch lower(type)
    case 'sf_long'
        Coeff = [
            mfparams.LFZO(1), ...
            mfparams.LCX(1), ...
            mfparams.LMUX(1), ...
            mfparams.LEX(1), ...
            mfparams.LKX(1), ...
            mfparams.LHX(1), ...
            mfparams.LVX(1), ...
            mfparams.FNOMIN(1), ...
            mfparams.NOMPRES(1) ...
            mfparams.LXAL
        ];

    case 'sf_lat'
        Coeff = [
            mfparams.LFZO(1), ...
            mfparams.LCY(1), ...
            mfparams.LMUY(1), ...
            mfparams.LEY(1), ...
            mfparams.LKY(1), ...
            mfparams.LKYC(1), ...
            mfparams.LKZC(1), ...
            mfparams.LHY(1), ...
            mfparams.LVY(1), ...
            mfparams.FNOMIN(1), ...
            mfparams.NOMPRES(1) ...
            mfparams.LYKA
        ];
    case 'sf_align'
        Coeff = [
            mfparams.LFZO
            mfparams.LMUY
            mfparams.LKY
            mfparams.LTR
            mfparams.LRES
            mfparams.LKYC
            mfparams.LKZC
            mfparams.UNLOADED_RADIUS
            mfparams.FNOMIN
            mfparams.NOMPRES
            mfparams.LS];

    otherwise
        error('Unknown coefficient type: %s', type);
end

end
